---
- name: Deploy Apache Web Server
  hosts: webservers
  become: yes

  tasks:

    - name: Install Apache
      package:
        name: apache2
        state: present

    - name: Configure Apache to listen on port 8080
      replace:
        path: /etc/apache2/ports.conf
        regexp: '^Listen 80$'
        replace: 'Listen 8080'

    - name: Configure VirtualHost to use port 8080
      replace:
        path: /etc/apache2/sites-available/000-default.conf
        regexp: '<VirtualHost \*:80>'
        replace: '<VirtualHost *:8080>'

    - name: Create webpage for VM1
      copy:
        dest: /var/www/html/index.html
        content: "Hello World from SJSU-1"
      when: inventory_hostname == "vm1"

    - name: Create webpage for VM2
      copy:
        dest: /var/www/html/index.html
        content: "Hello World from SJSU-2"
      when: inventory_hostname == "vm2"

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
        enabled: yes